name: Add a new instance
description: Add a new instance to searx.space
title: "Add https://<instance URL>"
labels:
  - instance add
  - instance

body:
  - type: markdown
    attributes:
      value: |
        ### General

        Enter your instance URL in the title above e.g: `Add https://searxng.example.com`

        ---

        Your instance will receive requests from the host `check.searx.space`:

        The IP addresses may change in the future, currently they are:
        - 167.235.158.251
        - 2a01:04f8:1c1c:8fc2::/64

        New instance requests are subject to a 2 week wait after approval to ensure the maintainer can keep their instance healthy and up to date.

  - type: checkboxes
    attributes:
      label: Requirements (make sure to read all of them)
      description: |
        You must comply with all the requirements for your instance to be added. If after we add your instance, it fails to respect all requirements, it will be removed.
        We also may modify these rules in the future, although you will be notified if your instance fails to respect the new requirements.
      options:
      - label: "This is my instance. I bought and own this domain myself. Shared domains (e.g. noip.com, eu.org) are not allowed."
        required: true
      - label: "I'll keep my instance up to date (no more than 1 week behind). Examples: watchtower, cron, diun, wud."
        required: true
      - label: "I will keep at least **90%** monthly uptime. If a long downtime is planned (7d+), ask for the instance to be removed."
        required: true
      - label: "I do not track the users of my instance with any analytics or tracking software."
        required: true
      - label: "I won't manipulate my instance ranking to gain an unfair advantage over other public instances (e.g. caching requests from searx.space)."
        required: true
      - label: "I control the webserver that terminates TLS for user requests. Examples of forbidden services: Cloudflare Proxy (orange cloud), PaaS (e.g. Heroku, Railway, Render), managed HTTP(S) load balancers (e.g. AWS ALB, Google Cloud HTTPS LB), shared web hosting. Examples of allowed services: TCP/L4 load balancers, Cloudflare DNS only (grey cloud)."
        required: true
      - label: "I acknowledge that managing a public instance is not an easy task and takes ongoing work to keep the instance healthy. (e.g. using a monitoring system)"
        required: true
      - label: "I will only restrict user access when needed to keep the instance working for everyone else (e.g. bots, attacks). Restrictions for other reasons are forbidden."
        required: true

  - type: checkboxes
    attributes:
      label: Bot protection
      description: |
        You must enable the `server.public_instance` parameter. [Documentation](https://github.com/searxng/searx-instances/discussions/417)
      options:
      - label: "Yes I have configured the `server.public_instance` parameter."
        required: true

  - type: markdown
    attributes:
      value: |
        ### Recommendations for your instance (rank higher on searx.space)
        - Harden the TLS security of your server by getting an [A+ TLS grade](https://cryptcheck.fr/).
          Look into the [TLS & CSP guide](https://github.com/searxng/searx-instances/discussions/849)
        - Harden the security of your users when they use your instance by getting an [A+ CSP grade](https://observatory.mozilla.org/).
          Look into the [TLS & CSP guide](https://github.com/searxng/searx-instances/discussions/849)
        - Configure IPv6 on your server: if your provider supports it, please enable it - the internet will thank you.

  - type: input
    id: matrix-username
    attributes:
      label: Matrix username
      description: |
        Please enter your full Matrix ID, including your homeserver.
        Example: @foobar:matrix.org
        
        You will receive an invite to the private instance owners room. 
        We discuss the troubles of managing a public instance, share advice (like how to defend your instance against bots), and also announce any big changes to searxng that may affect you.
    validations:
      required: false

  - type: input
    id: source-code-url
    attributes:
      label: Alternate source code
      description: |
        If you have modified SearXNG, publish your changes and make sure that they are accessible from your instance in order to comply with the AGPL.
    validations:
      required: false

  - type: textarea
    id: comments
    attributes:
      label: Comment
      description: |
        Optional comments about your instance.
