name: Add a new instance
description: Add a new instance to searx.space
title: "Add https://<instance URL>"
labels:
  - instance add
  - instance

body:
  - type: checkboxes
    attributes:
      label: General
      description: |
        Enter your instance URL in the title above ( For example: `Add https://searxng.example.com` )

        Your instance will receive requests from the host `check.searx.space` (the IP addresses of this host may change in the future).
        Currently, if you don't give the right to `check.searx.space` to check your instance, it is not possible to add your instance to the list.
      options:
      - label: "It is my instance."
        required: true
      - label: "I give the right to check.searx.space to check my instance (every 3 hours for the response times, every 24 hours for the other tests)."
        required: true
      - label: "I won't try to manipulate the ranking of my instance in a way that give an unfair advantage over the other public instances in the list. (e.g. caching requests for searx.space server)"
        required: true
      - label: "I guarantee to keep an uptime per month of my instance at **minimum 90%**. Your instance will be removed if you don't respect this rule."
        required: true

  - type: dropdown
    id: version
    attributes:
      label: Bot protection
      description: |
        Do you have installed a bot protection ?

        Be sure to have configured a bot protection:
        * once your instance is added to searx.space, it will receive requests from different bots which may increase its chance of getting blocked by various search engines.
        * removing your instance from searx.space won't stop the bots and thus will most likely not unblock it from the various search engines.

        We recommend the usage of [the built-in limiter plugin](https://docs.searxng.org/src/searx.plugins.limiter.html#limiter-plugin) if you are using SearXNG or [filtron](https://github.com/searxng/filtron) if you are using SearX.

        ⚠️ If you have installed [filtron](https://github.com/searxng/filtron), we urge you to use the [rules from searx-docker](https://github.com/searx/searx-docker/blob/master/rules.json). Please double check if you are using them.
      options:
        - "No, I have not installed a bot protection and I do recognize that without one, my instance will be flooded by bots and could have some of its engines stop working (an example is Google)."
        - "Yes, I have installed filtron (rules.json from searx-docker)."
        - "Yes, I have installed filtron (other rules)."
        - "Yes, I have enabled the limiter plugin built in SearXNG."
        - "Yes, I have installed another bot protection."
    validations:
      required: true

  - type: input
    id: source-code-url
    attributes:
      label: Source code URL
      description: |
        If you have modified the source code, please publish it to an URL and make sure that the URL is publicly accessible in your instance's site
        ( For searx instance, not for SearXNG instance: check your [settings.yml](https://github.com/searx/searx/blob/e88bea53ebf220648685cdb8eff017357728494e/searx/settings.yml#L8) )
        In case of issue, please specify the GIT URL here
    validations:
      required: false

  - type: textarea
    id: comments
    attributes:
      label: Comment
      description: |
        If you are using Apache, Nginx, you can use https://ssl-config.mozilla.org to get A+ TLS grade.
        You can use https://github.com/searxng/searx-docker/blob/master/Caddyfile#L33-L84 to get A+ HTML grade.

        Optional comment about your instance
